### ISSUE TITLE
rate limiting using redis backend error

### ISSUE THREAD

**Issue by weiztech** [Bogdanp/dramatiq#147]
i'm following documentation
https://dramatiq.io/cookbook.html#rate-limiting
and got error on running task with `rate limiting` using redis backend.
tested using dramatiq 1.4.0 with ubuntu 18.04

Traceback (most recent call last):
  File ".../env/lib/python3.6/site-packages/dramatiq/worker.py", line 397, in process_message
    res = actor(*message.args, **message.kwargs)
  File "..env/lib/python3.6/site-packages/dramatiq/actor.py", line 213, in __call__
    return self.fn(*args, **kwargs)
  File "./tasks.py", line 54, in print_current_date
    with ONE_CONCURRENT.acquire():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File ".../env/lib/python3.6/site-packages/dramatiq/rate_limits/rate_limiter.py", line 71, in acquire
    acquired = self._acquire()
  File "../env/lib/python3.6/site-packages/dramatiq/rate_limits/concurrent.py", line 45, in _acquire
    added = self.backend.add(self.key, 1, ttl=self.ttl)
AttributeError: 'RedisBackend' object has no attribute 'add'

**Comment by Bogdanp** [comment]
Could you post your setup code so I can see it? The redis backend for sure has an `add` method.

**Comment by Bogdanp** [comment]
You'll want to replace the line 

```python
from dramatiq.results.backends import RedisBackend
```

```python
from dramatiq.rate_limits.backends import RedisBackend
```

That should solve your issue!

**Comment by weiztech** [comment]
I thought its was the same class because the name is same.(just checked the code, its different..)
its fixed now.

Thanks!

**Comment by Bogdanp** [comment]
Yep, that's definitely confusing! Glad you got it fixed.

**Comment by Volhen** [comment]
Hello. Please tell me I used f`rom dramatiq.rate_limits.backends import RedisBackend` from the example above, but it gives an error like this:
```
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/dramatiq/worker.py", line 470, in process_message
    res = actor(*message.args, **message.kwargs)
  File ".../venv/lib/python3.6/site-packages/dramatiq/actor.py", line 145, in __call__
    result = self.fn(*args, **kwargs)
  File ".../task/fake.py", line 8, in print_current_date
    with ONE_CONCURRENT.acquire():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File ".../venv/lib/python3.6/site-packages/dramatiq/rate_limits/rate_limiter.py", line 71, in acquire
    acquired = self._acquire()
  File ".../venv/lib/python3.6/site-packages/dramatiq/rate_limits/concurrent.py", line 49, in _acquire
    return self.backend.incr(self.key, 1, maximum=self.limit, ttl=self.ttl)
  File ".../venv/lib/python3.6/site-packages/dramatiq/rate_limits/backends/redis.py", line 51, in incr
    pipe.watch(key)
  File ".../venv/lib/python3.6/site-packages/rediscluster/pipeline.py", line 304, in watch
    raise RedisClusterException("method watch() is not implemented")
rediscluster.exceptions.RedisClusterException: method watch() is not implemented
```
Thanks in advance!

**Comment by Volhen** [comment]
Please tell me how I can better organize the trotting process in dramatiq.
Thanks in advance!

**Comment by mitangelo** [comment]
Will rate limit RedisBackend   also let u get the results?

**Comment by mitangelo** [comment]
```
[2022-07-14 16:06:51,619] [PID 10] [Thread-4] [dramatiq.broker.RedisBroker] [CRITICAL] Unexpected failure in after_process_message of <dramatiq.results.middleware.Results object at 0x7f95b09e5fa0>.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/dramatiq/broker.py", line 114, in emit_after
    getattr(middleware, signal)(self, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/dramatiq/results/middleware.py", line 95, in after_process_message
    self.backend.store_result(message, result, result_ttl)
AttributeError: 'RedisBackend' object has no attribute 'store_result'```
