### ISSUE TITLE
Django rundramatiq discover tasks but fails to find Actors

### ISSUE THREAD

**Issue by davePlug** [Bogdanp/dramatiq#168]
# Issues
With a fairly simple setup, i created a Task, spinned a RabbitMQ and a **django rundramatiq** the message goes through but seems like dramatiq is not able to find the actor 

`
Running dramatiq: "dramatiq --path . --processes 16 --threads 16 --watch . django_dramatiq.setup django_dramatiq.tasks youtube.tasks"

[2019-02-12 14:09:37,439] [PID 24633] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.4.3' is booting up.
[2019-02-12 14:09:38,031] [PID 24645] [MainThread] [dramatiq.WorkerProcess(3)] [INFO] Worker process is ready for action.
[2019-02-12 14:09:38,031] [PID 24649] [MainThread] [dramatiq.WorkerProcess(7)] [INFO] Worker process is ready for action.
[2019-02-12 14:09:38,031] [PID 24657] [MainThread] [dramatiq.WorkerProcess(15)] [INFO] Worker process is ready for action.
...
...
[2019-02-12 14:10:01,230] [PID 24657] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [ERROR] Received message for undefined actor 'get_videos'. Moving it to the DLQ.
Traceback (most recent call last):
  File "/home/daveplug/.venv/bbtool/lib/python3.6/site-packages/dramatiq/worker.py", line 286, in handle_message
    actor = self.broker.get_actor(message.actor_name)
  File "/home/daveplug/.venv/bbtool/lib/python3.6/site-packages/dramatiq/broker.py", line 214, in get_actor
    raise ActorNotFound(actor_name) from None
dramatiq.errors.ActorNotFound: get_videos
`

## Checklist

* [ v] Does your title concisely summarize the problem?
* [ v] Did you include a minimal, reproducible example?
* [ v] What OS are you using?
* [ v] What version of Dramatiq are you using?
* [ v] What did you do?
* [ v] What did you expect would happen?
* [ v] What happened?

## What OS are you using?
Debian 7.3.0-19

## What version of Dramatiq are you using?
Dramatiq 1.4.3

## What did you do?
With a fairly simple setup, i created a Task, spinned a RabbitMQ and a **django rundramatiq** the message goes through but seems like dramatiq is not able to find the actor 

## What did you expect would happen?
To find the actor

**Comment by Bogdanp** [comment]
That's odd. Any chance you could share the contents of the `youtube.tasks` module?

**Comment by davePlug** [comment]
Basically empty...
`print("hello videos")`

**Comment by Bogdanp** [comment]
So where is `get_videos` defined then? Your tasks modules need to contain the actual task function definitions.

**Comment by davePlug** [comment]
yea, i correct myself:
```
import dramatiq

@dramatiq.actor
def get_videos(channel):
    print("GET_YT")
```

**Comment by davePlug** [comment]
@Bogdanp had a chance to look into this?

**Comment by Bogdanp** [comment]
I can take a look if you can upload the repo somewhere. Otherwise, I can't reproduce this so I assume it's a problem w/ your setup.

**Comment by davePlug** [comment]
Thank you @Bogdanp , here is a minimal repo to reproduce the error:
https://github.com/davePlug/django-dramatiq-test

**Comment by Bogdanp** [comment]
This is related to https://github.com/Bogdanp/django_dramatiq/issues/26 . I'm closing this issue in favor of that one and I'll release a fix (version `0.6.0`) for `django_dramatiq` in a few minutes.

**Comment by davePlug** [comment]
Lovely Thank you!
