### ISSUE TITLE
RabbitMQ Connection error leads to exception in dramatiq

### ISSUE THREAD

**Issue by bpereto** [Bogdanp/dramatiq#187]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://discuss.dramatiq.io).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Manjaro Linux

## What version of Dramatiq are you using?

1.5.0

## What did you do?

* Start RabbitMQ (docker)
* Start Dramatiq (the basic example)
* stop docker container of rabbitmq (gracefully)

## What did you expect would happen?

daramtiq emits error without exception

## What happened?
dramatiq emits error and an python exception.

```
[2019-03-13 18:01:12,043] [PID 12223] [Thread-3] [dramatiq.worker.ConsumerThread(default)] [CRITICAL] Consumer encountered a connection error: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
[2019-03-13 18:01:12,043] [PID 12223] [Thread-3] [dramatiq.worker.ConsumerThread(default)] [INFO] Restarting consumer in 3.00 seconds.
[2019-03-13 18:01:12,043] [PID 12223] [Thread-3] [dramatiq.brokers.rabbitmq._RabbitmqConsumer] [ERROR] Failed to wait for all callbacks to complete.  This can happen when the RabbitMQ server is suddenly restarted.
Traceback (most recent call last):
  File "/home/beni/devel/test/dramatiq/.venv/lib/python3.7/site-packages/dramatiq/brokers/rabbitmq.py", line 458, in close
    self.connection.add_callback_threadsafe(all_callbacks_handled.set)
  File "/home/beni/devel/test/dramatiq/.venv/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 675, in add_callback_threadsafe
    functools.partial(self._on_threadsafe_callback, callback))
  File "/home/beni/devel/test/dramatiq/.venv/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 163, in add_callback_threadsafe
    self.ioloop.add_callback_threadsafe(callback)
  File "/home/beni/devel/test/dramatiq/.venv/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 397, in add_callback_threadsafe
    self._callbacks.append(callback)
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by Bogdanp** [comment]
This is intentional albeit a bit ugly when it does happen.  IMO it's better to log the stack trace than not since we have to throw a fairly wide net to even handle these exceptions gracefully.

**Comment by Negashev** [comment]
@Bogdanp what solution for this problem?

**Comment by RAishwarya1103** [comment]
@Bogdanp Do we have a solution for this error?

**Comment by LincolnPuzey** [comment]
Using Dramatiq 2.1.0 the logs I see is now 

```text
[...] [dramatiq.worker.ConsumerThread(default)] [CRITICAL] Consumer encountered a connection error: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
[...] [dramatiq.worker.ConsumerThread(default)] [INFO] Restarting consumer in 3.00 seconds.
[...] [dramatiq.brokers.rabbitmq._RabbitmqConsumer] [ERROR] Failed to wait for all callbacks to complete.  This can happen when the RabbitMQ server is suddenly restarted.
Traceback (most recent call last):
  File "/home/lincoln/seaf/offshore-renewable-energy/.venv/lib/python3.13/site-packages/dramatiq/brokers/rabbitmq.py", line 599, in close
    self.connection.add_callback_threadsafe(all_callbacks_handled.set)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lincoln/seaf/offshore-renewable-energy/.venv/lib/python3.13/site-packages/pika/adapters/blocking_connection.py", line 742, in add_callback_threadsafe
    raise exceptions.ConnectionWrongStateError(
        'BlockingConnection.add_callback_threadsafe() called on '
        'closed or closing connection.')
pika.exceptions.ConnectionWrongStateError: BlockingConnection.add_callback_threadsafe() called on closed or closing connection.
```

@Bogdanp I would rather fix this so no stacktrace is logged.
My general approach is, if a stacktrace it logged is means a bug needs to be fixed somewhere.

Here I would expect the errors from the server shutdown to log errors, but no stacktrace.
