### ISSUE TITLE
RabbitMQ broker doesn't close connections?

### ISSUE THREAD

**Issue by CWN** [Bogdanp/dramatiq#217]
# Issues

Hi, I have some log flooding "problem" when using dramatiq actor from APScheduler

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

CentOS Linux release 7.6.1810 (Core)

## What version of Dramatiq are you using?

1.6.0

## What did you do?

Create simple task for printing current time

clock_func.py
```python
from datetime import datetime
import dramatiq

@dramatiq.actor(max_retries=1, max_age=5_000, time_limit=5_000)
def current_time():
    print('>> Current Timestamp: {datetime}'.format(datetime=datetime.now().strftime('%Y-%m-%d %H-%M-%S.%f')))
```
Sending it from APScheduler daemon (script preparead for using as systemd service):
```python
#!/opt/melodrama/venv/bin/python36

import logging
import os
import signal
import sys
import time

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

from clock_func import current_time

logging.basicConfig(filename='scheduler.log',format='%(asctime)s[%(name)s][%(levelname)s]: %(message)s')

logging.getLogger('apscheduler').setLevel(logging.DEBUG)


def main():
    scheduler = BackgroundScheduler()
    scheduler.start()

    scheduler.add_job(
        current_time.send,
        CronTrigger.from_crontab("* * * * *"),
    )

    def shutdown(signum, frame):
        logging.getLogger('apscheduler').info('Shutdown automata scheduler')
        scheduler.shutdown()
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    logging.getLogger('apscheduler').info('Starting automata scheduler')

    while True:
        time.sleep(1)


if __name__ == "__main__":
    main()

```

## What did you expect would happen?

All work fine, once a minute generates message and dramatiq accept and run task. BUT!

## What happened?
After some time in scheduler.log occured and spammed messages like this:
```
2019-07-03 15:06:00,006[pika.adapters.utils.io_services_utils][ERROR]: _AsyncBaseTransport._produce() failed, aborting connection: error=ConnectionResetError(104, 'Connection reset by peer'); sock=<socket.socket fd=19, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 49852)>; Caller's stack:
Traceback (most recent call last):
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 820, in _produce
    self._tx_buffers[0])
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 820, in _produce
    self._tx_buffers[0])
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/opt/portal/portal/venv/lib64/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
2019-07-03 15:06:00,006[pika.adapters.base_connection][ERROR]: connection_lost: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
2019-07-03 15:06:00,012[pika.adapters.blocking_connection][ERROR]: Unexpected connection close detected: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)

```

In rabbitmq.log I see errors like this:
```
[error] <0.13852.1> closing AMQP connection <0.13852.1> (127.0.0.1:49868 -> 127.0.0.1:5672):
missed heartbeats from client, timeout: 5s
```

Herewith task messages generates as usual and all working fine. It's looks like on every send dramatiq creates new connection to rabbitMQ, but not closing it and rabbit killing it.

So, **how to fix this?**

**Comment by Bogdanp** [comment]
You have two options:

* either you can increase your [heartbeat timeout](https://pika.readthedocs.io/en/stable/modules/parameters.html?highlight=connection#pika.connection.ConnectionParameters.heartbeat) (`RabbitmqBroker(heartbeat=600)`) to >1m (it looks like yours is currently 5s from the rmq logs, which is unusual) or
* close the connection after every send via `get_broker().connection.close()`.
