### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by yanxiu0614** [Bogdanp/dramatiq#222]
# Issues

OS: Ubuntu 18.04

python:3.6.8

broker：redis

command: dramatiq_gevent --process 1 --thread 2 （moudle）

Error messages and/or stack traces of the bug:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/gevent/threading.py", line 177, in run
    super(Thread, self).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dramatiq/cli.py", line 265, in watch_logs
    data = event.recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
MemoryError

PS:Everything works fine when I am not using the dramatiq.

**Comment by Bogdanp** [comment]
Sorry, but it's unlikely Dramatiq is the cause here. Your system is running out of memory or memory can't be allocated for whatever reason.
