### ISSUE TITLE
Possible bug with 1.7.0

### ISSUE THREAD

**Issue by LiteWait** [Bogdanp/dramatiq#233]
This actor seems to run fine, but all sudden I see the error below:

```
Unhandled error during post_process_message(publish_changes_do_work({'create_full': False}, initiated_by='SCHEDULE', enterprise_id=1504)).  You've found a bug in Dramatiq.  Please report it!
Although your message has been processed, it will be processed again once this worker is restarted.

Traceback (most recent call last):
  File "XXXX/site-packages/dramatiq/worker.py", line 341, in post_process_message
    self.consumer.ack(message)
  File "XXXX/site-packages/dramatiq/brokers/redis.py", line 284, in ack
    self.broker.do_ack(self.queue_name, message.options["redis_message_id"])
  File "XXXX/site-packages/dramatiq/brokers/redis.py", line 256, in do_dispatch
    return dispatch(args=args, keys=keys)
  File "XXXX/site-packages/redis/client.py", line 2944, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "XXXX/site-packages/redis/client.py", line 2079, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "XXXX/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "XXXX/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "XXXX/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to 
```f_605aad1746512fb86e8ee6fa6129dccdf32eed59): @user_script:169: WRONGTYPE Operation against a key holding the wrong kind of value
~
```
Another of a similar error:

NOTE: This seems to be when the worker is trying to process the delay (.XQ) messages.  That is the only queue than has messages when I looked at Redis.

```
XXXX/python3.6/site-packages/dramatiq/worker.py] [lineno 269] [priority CRITICAL] [funcname run] Consumer encountered an unexpected error.
Traceback (most recent call last):
  File "XXXX/python3.6/site-packages/dramatiq/brokers/redis.py", line 315, in __next__
    data = self.message_cache.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "XXXX/python3.6/site-packages/dramatiq/worker.py", line 253, in run
    for message in self.consumer:
  File "XXXX/python3.6/site-packages/dramatiq/brokers/redis.py", line 328, in __next__
    self.prefetch - self.message_refc,
  File "XXXX/python3.6/site-packages/dramatiq/brokers/redis.py", line 256, in do_dispatch
    return dispatch(args=args, keys=keys)
  File "XXXX/python3.6/site-packages/redis/client.py", line 2944, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "XXXX/python3.6/site-packages/redis/client.py", line 2079, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "XXXX/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "XXXX/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "XXXX/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_605aad1746512fb86e8ee6fa6129dccdf32eed59): @user_script:88: WRONGTYPE Operation against a key holding the wrong kind of value
```

**Comment by Sovetnikov** [comment]
Error messages pointing to this lines in dispatch.lua (redis queue management script):
```
88 local message_ids = redis.call("smembers", dead_worker_queue_acks)
169 redis.call("srem", queue_acks, message_id)
```
Seems acks queue storage in redis is not SET, but some other type. This may be in case dramatiq upgrade?

Check with redis-cli:
find acks queues - KEYS *__acks__*
check types of storage - TYPE <acks queue key>

You can DEL <acks queue key> to clear wrong data and i think all will work.
Or you can drop redis database with FLUSHDB

**Comment by LiteWait** [comment]
Thanks. It hasn't happened again. I've been running 1.7.0 with Redis all along, doubt its an upgrade issue.  More worried about the second error I reported.

**Comment by Bogdanp** [comment]
@LiteWait are you running Redis with an eviction policy by any chance?

**Comment by LiteWait** [comment]
noeviction

we are in testing not production, so clearing we aren't bumping into memory
limits or anything like that.

thanks.

**Comment by Bogdanp** [comment]
Please give version 1.8.0 a try (will be released later today) and let me know if this is still a problem for you.

**Comment by Bogdanp** [comment]
I'm closing this for now. Feel free to re-open if this is still an issue on the latest release.
