### ISSUE TITLE
Error on starting rundramatiq command

### ISSUE THREAD

**Issue by kordsmi** [Bogdanp/dramatiq#249]
If I create folder tasks for my own needs and it not a python package an error occures:

```
 * Discovered tasks module: 'route_sheet.tasks'
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mikhail/.cache/pypoetry/virtualenvs/t12-backend-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mikhail/.cache/pypoetry/virtualenvs/t12-backend-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mikhail/.cache/pypoetry/virtualenvs/t12-backend-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mikhail/.cache/pypoetry/virtualenvs/t12-backend-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/mikhail/.cache/pypoetry/virtualenvs/t12-backend-py3.7/lib/python3.7/site-packages/django_dramatiq/management/commands/rundramatiq.py", line 85, in handle
    tasks_modules = self.discover_tasks_modules()
  File "/home/mikhail/.cache/pypoetry/virtualenvs/t12-backend-py3.7/lib/python3.7/site-packages/django_dramatiq/management/commands/rundramatiq.py", line 125, in discover_tasks_modules
    elif not self._is_package(imported_module):
  File "/home/mikhail/.cache/pypoetry/virtualenvs/t12-backend-py3.7/lib/python3.7/site-packages/django_dramatiq/management/commands/rundramatiq.py", line 142, in _is_package
    return module_path and os.path.isdir(module_path[0])
TypeError: '_NamespacePath' object is not subscriptable
```

I think it's worth adding a check for the type _NamespacePath in the _is_package method

**Comment by Bogdanp** [comment]
I'll take a PR for this if it's not too much effort, otherwise I don't know when I'll get to it. I'm going to close this, though, since this is the wrong repo. Feel free to open a new issue in the `django_dramatiq` repo.
