### ISSUE TITLE
OSError: [Errno 98] Address already in use exception when running multiple dramatiq processes

### ISSUE THREAD

**Issue by yurayakimenko** [Bogdanp/dramatiq#280]
Hi. Got this strange issue since v1.8.0 when running multiple workers. I've tried v1.7.0 and it's working perfect. First one worker starts normally, without any warnings:

`dramatiq task_queues.btc --processes 1 --threads 1 --queues btc`

```
[2020-02-28 08:29:35,813] [PID 57498] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.8.1' is booting up.
[2020-02-28 08:29:35,813] [PID 57500] [MainThread] [dramatiq.WorkerProcess(0)] [INFO] Worker process is ready for action.
[2020-02-28 08:29:35,814] [PID 57506] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Fork process 'dramatiq.middleware.prometheus:_run_exposition_server' is ready for action.
```

But the second one:

`dramatiq task_queues.eth --processes 1 --threads 1 --queues eth --verbose`

```
[2020-02-28 08:47:19,235] [PID 60175] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.8.1' is booting up.
[2020-02-28 08:47:19,209] [PID 60177] [MainThread] [dramatiq.WorkerProcess(0)] [DEBUG] Loading broker...
[2020-02-28 08:47:19,233] [PID 60177] [MainThread] [dramatiq.middleware.prometheus.Prometheus] [DEBUG] Setting up metrics...
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.WorkerProcess(0)] [DEBUG] Loading modules...
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.WorkerProcess(0)] [DEBUG] Sending forks to main process...
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.WorkerProcess(0)] [DEBUG] Starting worker threads...
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for queue 'btc'.
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.worker.Worker] [DEBUG] Dropping consumer for queue 'btc': not whitelisted.
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for delay queue 'btc.DQ'.
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.worker.Worker] [DEBUG] Dropping consumer for queue 'btc.DQ': not whitelisted.
[2020-02-28 08:47:19,234] [PID 60177] [Thread-2] [dramatiq.worker.WorkerThread] [DEBUG] Running worker thread...
[2020-02-28 08:47:19,234] [PID 60177] [MainThread] [dramatiq.WorkerProcess(0)] [INFO] Worker process is ready for action.
[2020-02-28 08:47:19,235] [PID 60182] [MainThread] [dramatiq.ForkProcess(0)] [DEBUG] Loading fork function...
[2020-02-28 08:47:19,235] [PID 60182] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Fork process 'dramatiq.middleware.prometheus:_run_exposition_server' is ready for action.
[2020-02-28 08:47:19,236] [PID 60182] [MainThread] [dramatiq.middleware.prometheus._run_exposition_server] [DEBUG] Starting exposition server...
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yy/Documents/PyProjects/task_queues/venv/lib/python3.7/site-packages/dramatiq/cli.py", line 416, in fork_process
    return sys.exit(func())
  File "/home/yy/Documents/PyProjects/task_queues/venv/lib/python3.7/site-packages/dramatiq/middleware/prometheus.py", line 182, in _run_exposition_server
    httpd = HTTPServer(address, _metrics_handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

I've tried both with `--processes --threads --queues` flags and without them. The same issue reproducing. But worker still able to consume tasks, btw. It seems like you are trying to boot up another HTTPServer for Prometheus metrics on the same port, ignoring that it's already running.

**Comment by yurayakimenko** [comment]
The workaround is to setup exposition server separately, removing Prometheus from the list of default middlewares by overriding default Broker for your project:

`your_project/tasks/broker.py`

```
import dramatiq
from dramatiq.brokers.rabbitmq import RabbitmqBroker
from dramatiq.middleware.age_limit import AgeLimit
from dramatiq.middleware.callbacks import Callbacks
from dramatiq.middleware.pipelines import Pipelines
from dramatiq.middleware.retries import Retries
from dramatiq.middleware.shutdown import ShutdownNotifications
from dramatiq.middleware.time_limit import TimeLimit

broker_middleware = [
    AgeLimit, TimeLimit, ShutdownNotifications, Callbacks, Pipelines, Retries
]

rabbitmq_broker = RabbitmqBroker(
    host="127.0.0.1",
    port=5672,
    heartbeat=60,
    connection_attempts=5,
    blocked_connection_timeout=30,
    middleware=broker_middleware
)
dramatiq.set_broker(rabbitmq_broker)
```

`your_project/tasks/prometheus_exposition_server.py`
```
from dramatiq.middleware.prometheus import _run_exposition_server

if __name__ == '__main__':
    _run_exposition_server()
```

**Comment by ringge** [comment]
so as of now we still have to use the above workaround? It's not possible to run multiple dramatiq processes yet?
