### ISSUE TITLE
redis.exceptions.ResponseError: @user_script:218: @user_script: 218: Lua redis() command arguments must be strings or integers

### ISSUE THREAD

**Issue by vkatochka** [Bogdanp/dramatiq#320]
Dramatiq 1.9.0
Redis server v=5.0.7, redis-cli 5.0.7
Ubuntu 18.04.4 LTS
Python 3.6.9

~~~
@dramatiq.actor(max_retries=0,max_age=((2*60*1000)+10000),time_limit=((2*60*1000)+10000))
def mkss(sid,uuid,prms):
	...
 ~~~

~~~
[2020-06-17 07:30:48,475] [PID 2044] [Thread-4] [dramatiq.middleware.age_limit.AgeLimit] [WARNING] Message 'unique-1592378746761-5ee9c57a55536e1fe1518ad6' has exceeded its age limit.
[2020-06-17 07:30:48,477] [PID 2044] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [ERROR] Unhandled error during post_process_message(mkss('5ee9c57a55536e1fe1518ad6', 'unique-1592378746761-5ee9c57a55536e1fe1518ad6', {...})).  You've found a bug in Dramatiq.  Please report it!
Although your message has been processed, it will be processed again once this worker is restarted.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dramatiq/worker.py", line 335, in post_process_message
    self.consumer.nack(message)
  File "/usr/local/lib/python3.6/dist-packages/dramatiq/brokers/redis.py", line 317, in nack
    self.broker.do_nack(self.queue_name, message.options["redis_message_id"])
  File "/usr/local/lib/python3.6/dist-packages/dramatiq/brokers/redis.py", line 275, in do_dispatch
    return dispatch(args=args, keys=keys)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 4073, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 3143, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_e9668bc413bd4a2d63c8108b124f5b7df0d01263): @user_script:218: @user_script: 218: Lua redis() command arguments must be strings or integers
~~~

**Comment by swidoff** [comment]
Changing line 215 of dispatch.lua seems to work? 

```
if message then
        redis.call("zadd", xqueue_full_name, timestamp, message_id)
        redis.call("hset", xqueue_messages, message_id, message)
        redis.call("hdel", queue_messages, message_id)
end
```

This is my first foray into lua, but according to the [docs](http://www.lua.org/manual/5.3/manual.html#2.1): "The type boolean has two values, false and true. Both nil and false make a condition false; any other value makes it true."

I have no idea why `message =~ nil` doesn't work (or sometimes doesn't work).

**Comment by swidoff** [comment]
> I have no idea why `message =~ nil` doesn't work (or sometimes doesn't work).

I know now. :)

`redis.call("hget", ...)` returns false and not nil if the key is not found...

https://github.com/Bogdanp/dramatiq/pull/323

**Comment by Bogdanp** [comment]
Thanks again @swidoff . @vkatochka, please let us know if you still run into the issue with @swidoff 's changes.

**Comment by Bogdanp** [comment]
Closing this for now. Feel free to re-open if the bug is still present.
