### ISSUE TITLE
"No module named 'pika'" Error when using redis.

### ISSUE THREAD

**Issue by KonstantinSchubert** [Bogdanp/dramatiq#327]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

## What OS are you using?

macos

## What version of Dramatiq are you using?

1.9.0

## What did you do?

New python3 virtualenv:
```
pip install 'dramatiq[redis]'

python
>>> from dramatiq import actor
>>> @actor
>>> def test():
>>>    print("hello")
```

## What did you expect would happen?

It should run without error.

## What happened?

The following import error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/konstantninschubert/.virtualenvs/test2/lib/python3.7/site-packages/dramatiq/actor.py", line 233, in actor
    return decorator(fn)
  File "/Users/konstantninschubert/.virtualenvs/test2/lib/python3.7/site-packages/dramatiq/actor.py", line 217, in decorator
    broker = broker or get_broker()
  File "/Users/konstantninschubert/.virtualenvs/test2/lib/python3.7/site-packages/dramatiq/broker.py", line 35, in get_broker
    from .brokers.rabbitmq import RabbitmqBroker
  File "/Users/konstantninschubert/.virtualenvs/test2/lib/python3.7/site-packages/dramatiq/brokers/rabbitmq.py", line 25, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
```

**Comment by Bogdanp** [comment]
You need to set the broker to something else before you define your actor.

This would work:

```
python
>>> from dramatiq import actor, set_broker
>>> from dramatiq.brokers.redis import RedisBroker
>>> set_broker(RedisBroker())
>>> @actor
>>> def test():
>>>    print("hello")
```
