### ISSUE TITLE
Bug: Results-middleware doesn't handle ActorNotFound correctly

### ISSUE THREAD

**Issue by AndreCimander** [Bogdanp/dramatiq#336]
## What OS are you using?

Arch Linux

## What version of Dramatiq are you using?

1.9.0

## What did you do?

Adding a missing-actor message to simulate a staged deployment where events still reference old task names.

## What did you expect would happen?

I expected one handled exception (ActorNotFound) with a follow-up action where the message is moved to the DLQ, not a  `[CRITICAL] Unexpected failure in after_nack.` due to the result middleware.

## What happened?

```
[ERROR] Received message for undefined actor ''. Moving it to the DLQ.
python_worker_1      | Traceback (most recent call last):
python_worker_1      |   File "/usr/local/lib/python3.8/site-packages/dramatiq/worker.py", line 314, in handle_message
python_worker_1      |     actor = self.broker.get_actor(message.actor_name)
python_worker_1      |   File "/usr/local/lib/python3.8/site-packages/dramatiq/broker.py", line 214, in get_actor
python_worker_1      |     raise ActorNotFound(actor_name) from None
python_worker_1      | dramatiq.errors.ActorNotFound: ''
python_worker_1      | [2020-08-30 16:24:37,067] [PID 20] [Thread-2] [dramatiq.broker.ExchangeSupportedRabbitmqBroker] [CRITICAL] Unexpected failure in after_nack.
python_worker_1      | Traceback (most recent call last):
python_worker_1      |   File "./utils/dramatiq/brokers.py", line 61, in emit_after
python_worker_1      |     middleware_handler(self, *args, **kwargs)
python_worker_1      |   File "/usr/local/lib/python3.8/site-packages/dramatiq/results/middleware.py", line 95, in after_nack
python_worker_1      |     store_results, result_ttl = self._lookup_options(broker, message)
python_worker_1      |   File "/usr/local/lib/python3.8/site-packages/dramatiq/results/middleware.py", line 84, in _lookup_options
python_worker_1      |     actor = broker.get_actor(message.actor_name)
python_worker_1      |   File "/usr/local/lib/python3.8/site-packages/dramatiq/broker.py", line 214, in get_actor
python_worker_1      |     raise ActorNotFound(actor_name) from None
python_worker_1      | dramatiq.errors.ActorNotFound: ''
``` 

## Solution:

In `dramatiq.results.middleware.Results._lookup_options:84` change the actor fetch to handle missing actors:

```python
    def _lookup_options(self, broker, message):
        try:
             actor = broker.get_actor(message.actor_name)
        except ActorNotFound:
             return False, 0
```

I'll submit a PR in a few minutes :)

**Comment by Bogdanp** [comment]
Thnaks for the fix. This is now in master and will be released in the next few weeks.
