### ISSUE TITLE
Customizing middleware list causes `TypeError: unsupported operand type(s) for |=: 'set' and 'property'`

### ISSUE THREAD

**Issue by swaroopch** [Bogdanp/dramatiq#348]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [X] Does your title concisely summarize the problem?
* [X] Did you include a minimal, reproducible example?
* [X] What OS are you using?
* [X] What version of Dramatiq are you using?
* [X] What did you do?
* [X] What did you expect would happen?
* [X] What happened?

## What OS are you using?

debian buster

## What version of Dramatiq are you using?

1.9.0

## What did you do?

```python
"""
To reproduce `E   TypeError: unsupported operand type(s) for |=: 'set' and 'property'`

1. docker run -d -p 6379:6379 redis:latest
2. docker run --interactive --tty --rm --volume $PWD:/code --workdir /code python:3.6 bash
3. pip install -U dramatiq[redis]
4. python this_file.py
"""

from dramatiq import middleware
from dramatiq.brokers.redis import RedisBroker

# This Works

RedisBroker(
    url="redis://127.0.0.1",
)

# This Does Not Work

# File site-packages/dramatiq/broker.py", line 135, in add_middleware
# self.actor_options |= middleware.actor_options
# TypeError: unsupported operand type(s) for |=: 'set' and 'property'
# https://github.com/Bogdanp/dramatiq/blob/408c4f23b0a5db51f50ec592386ff168096d0551/dramatiq/broker.py#L135

RedisBroker(
    url="redis://127.0.0.1",
    middleware=[
        middleware.AgeLimit,
    ]
)
```

## What did you expect would happen?

No exceptions

## What happened?

Exception:

```
root@be1ee0359c53:/code# python customize_middleware.py
Traceback (most recent call last):
  File "run_locally.py", line 29, in <module>
    middleware.AgeLimit,
  File "/usr/local/lib/python3.6/site-packages/dramatiq/brokers/redis.py", line 98, in __init__
    super().__init__(middleware=middleware)
  File "/usr/local/lib/python3.6/site-packages/dramatiq/broker.py", line 84, in __init__
    self.add_middleware(m)
  File "/usr/local/lib/python3.6/site-packages/dramatiq/broker.py", line 135, in add_middleware
    self.actor_options |= middleware.actor_options
TypeError: unsupported operand type(s) for |=: 'set' and 'property'
```

**Comment by Bogdanp** [comment]
You need to pass an instance of the middleware into the list, not the middleware class.

```python

RedisBroker(
    url="redis://127.0.0.1",
    middleware=[
        middleware.AgeLimit(), # <-- here
    ]
)
```

rather than

```python
RedisBroker(
    url="redis://127.0.0.1",
    middleware=[
        middleware.AgeLimit, # <-- here
    ]
)
```
