### ISSUE TITLE
Support running code at worker startup

### ISSUE THREAD

**Issue by rouge8** [Bogdanp/dramatiq#350]
It would be really useful to be able to run worker code at startup similar to `celery.signal.worker_init`. This would make it easier to configure Dramatiq as part of app initialization (e.g. https://www.reddit.com/r/dramatiq/comments/h970tr/integrating_dramatiq_with_app_initialization/). Currently, we have our own wrapper for the Dramatiq CLI, roughly like:

```python
import click
from dramatiq.cli import main as dramatiq_worker
from dramatiq.cli import make_argument_parser
from pyramid import paster
from pyramid import path

@click.command()
@click.option("--config", type=click.Path(exists=True, dir_okay=False, resolve_path=True), default="local.ini")
@click.option("--queue", type=click.STRING, multiple=True)
def worker(queue):
    paster.setup_logging(config)
    # setup our pyramid app which includes dramatiq broker initialization and configuration
    settings = paster.get_appsettings(config)

    # Broker is the first position arg for dramatiq's cli which we are wrapping
    # We must at least send a valid module. But by not sending the name of a
    # broker (example: 'my.module:my_broker'), it will default to use the global
    # broker from ``dramatiq.get_broker()`` which lazily allows us to bootstrap
    # our application and set the global broker before running the CLI
    # https://github.com/Bogdanp/dramatiq/blob/v1.9.0/dramatiq/cli.py#L119
    command = [__name__]
    # Pyramid already bootstraps our logging config
    command += ["--skip-logging"]
    # Add queues
    if queue:
        command += ["--queues"] + list(queue)
    # Start the worker
    parser = make_argument_parser()
    args = parser.parse_args(command)
    dramatiq_worker(args)
```

This works when we use `fork` to spawn processes, but if you run dramatiq with `--spawn` or are on macOS or Windows and are on Python 3.8 and multiprocessing uses `spawn`, then no memory is shared with the workers and all of that application and broker config is lost.

If you have any ideas for how you'd do this, I might be able to help with implementation.

**Comment by Bogdanp** [comment]
I hadn't seen your Reddit post, but a custom middleware is the intended way to do this. Is there any reason why that doesn't work for you?

**Comment by rouge8** [comment]
Not my post, just one I'd found with a similar issue. Custom middleware doesn't help in this situation, because when using `dramatiq --use-spawn` (or running dramatiq on macOS with Python 3.8 or newer or on Windows with any Python version), memory isn't shared from the parent process so the broker configuration is lost.

Here's a fully functioning example:

```python
import multiprocessing

import click
import dramatiq
from dramatiq.brokers.redis import RedisBroker
from dramatiq.cli import main as dramatiq_worker
from dramatiq.cli import make_argument_parser
from dramatiq.middleware import Middleware

class DebugMiddleware(Middleware):
    def before_worker_boot(self, broker, worker):
        print(f"before booting {worker}")

    def after_worker_boot(self, broker, worker):
        print(f"after booting {worker}")

def configure_broker():
    broker = RedisBroker()
    broker.add_middleware(DebugMiddleware())
    dramatiq.set_broker(broker)

@click.command()
@click.option(
    "--multiprocessing-mode", type=click.Choice(["fork", "spawn"]), required=True
)
def worker(multiprocessing_mode):
    multiprocessing.set_start_method(multiprocessing_mode, force=True)

    configure_broker()

    command = [__name__]

    # Start the worker
    parser = make_argument_parser()
    args = parser.parse_args(command)
    dramatiq_worker(args)

if __name__ == "__main__":
    worker()
```

If you run this script with `--multi-processing-mode=fork`, the configured `RedisBroker` will be used and the middleware will run:

```console
$ python3.8 t.py --multiprocessing-mode fork
[2020-10-13 23:55:46,228] [PID 85400] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.9.0' is booting up.
before booting <dramatiq.worker.Worker object at 0x10538aaf0>
after booting <dramatiq.worker.Worker object at 0x10538aaf0>
[2020-10-13 23:55:46,217] [PID 85401] [MainThread] [dramatiq.WorkerProcess(0)] [INFO] Worker process is ready for action.
before booting <dramatiq.worker.Worker object at 0x10538aee0>
after booting <dramatiq.worker.Worker object at 0x10538aee0>
[2020-10-13 23:55:46,213] [PID 85402] [MainThread] [dramatiq.WorkerProcess(1)] [INFO] Worker process is ready for action.
before booting <dramatiq.worker.Worker object at 0x1053942e0>
after booting <dramatiq.worker.Worker object at 0x1053942e0>
[2020-10-13 23:55:46,215] [PID 85403] [MainThread] [dramatiq.WorkerProcess(2)] [INFO] Worker process is ready for action.
before booting <dramatiq.worker.Worker object at 0x1053946a0>
after booting <dramatiq.worker.Worker object at 0x1053946a0>
[2020-10-13 23:55:46,221] [PID 85404] [MainThread] [dramatiq.WorkerProcess(3)] [INFO] Worker process is ready for action.
before booting <dramatiq.worker.Worker object at 0x105394a60>
after booting <dramatiq.worker.Worker object at 0x105394a60>
[2020-10-13 23:55:46,220] [PID 85405] [MainThread] [dramatiq.WorkerProcess(4)] [INFO] Worker process is ready for action.
before booting <dramatiq.worker.Worker object at 0x105394e20>
after booting <dramatiq.worker.Worker object at 0x105394e20>
[2020-10-13 23:55:46,224] [PID 85406] [MainThread] [dramatiq.WorkerProcess(5)] [INFO] Worker process is ready for action.
before booting <dramatiq.worker.Worker object at 0x10539c220>
after booting <dramatiq.worker.Worker object at 0x10539c220>
[2020-10-13 23:55:46,222] [PID 85407] [MainThread] [dramatiq.WorkerProcess(6)] [INFO] Worker process is ready for action.
before booting <dramatiq.worker.Worker object at 0x10539b5e0>
after booting <dramatiq.worker.Worker object at 0x10539b5e0>
[2020-10-13 23:55:46,226] [PID 85408] [MainThread] [dramatiq.WorkerProcess(7)] [INFO] Worker process is ready for action.
[2020-10-13 23:55:46,231] [PID 85417] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Fork process 'dramatiq.middleware.prometheus:_run_exposition_server' is ready for action.
```

If you run it with `--multiprocess-mode=spawn`, it uses `dramatiq.get_broker()` which gets a default `RabbitmqBroker`. This is easy to demonstrate because I don't have `pika` installed in my virtualenv, but even with `pika` installed you'll see the middleware isn't used:

```console
$ python3.8 t.py --multiprocessing-mode spawn
[2020-10-13 23:57:20,216] [PID 85515] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.9.0' is booting up.
[2020-10-13 23:57:20,217] [PID 85515] [MainThread] [dramatiq.MainProcess] [CRITICAL] Worker with PID 85517 exited unexpectedly (code 2). Shutting down...
[2020-10-13 23:57:19,152] [PID 85517] [MainThread] [dramatiq.WorkerProcess(0)] [ERROR] Failed to import module.
Traceback (most recent call last):
  File "/Users/andy/.virtualenvs/gold/lib/python3.8/site-packages/dramatiq/cli.py", line 330, in worker_process
    module, broker = import_broker(args.broker)
  File "/Users/andy/.virtualenvs/gold/lib/python3.8/site-packages/dramatiq/cli.py", line 122, in import_broker
    return module, get_broker()
  File "/Users/andy/.virtualenvs/gold/lib/python3.8/site-packages/dramatiq/broker.py", line 35, in get_broker
    from .brokers.rabbitmq import RabbitmqBroker
  File "/Users/andy/.virtualenvs/gold/lib/python3.8/site-packages/dramatiq/brokers/rabbitmq.py", line 25, in <module>
    import pika
ModuleNotFoundError: No module named 'pika'
```

And with `pika`:

```console
$ python3.8 t.py --multiprocessing-mode spawn
[2020-10-13 23:58:20,815] [PID 85570] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.9.0' is booting up.
[2020-10-13 23:58:20,811] [PID 85572] [MainThread] [dramatiq.WorkerProcess(0)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:20,789] [PID 85573] [MainThread] [dramatiq.WorkerProcess(1)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:20,805] [PID 85574] [MainThread] [dramatiq.WorkerProcess(2)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:20,801] [PID 85575] [MainThread] [dramatiq.WorkerProcess(3)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:20,801] [PID 85576] [MainThread] [dramatiq.WorkerProcess(4)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:20,805] [PID 85577] [MainThread] [dramatiq.WorkerProcess(5)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:20,800] [PID 85578] [MainThread] [dramatiq.WorkerProcess(6)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:20,803] [PID 85579] [MainThread] [dramatiq.WorkerProcess(7)] [INFO] Worker process is ready for action.
[2020-10-13 23:58:21,079] [PID 85591] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Fork process 'dramatiq.middleware.prometheus:_run_exposition_server' is ready for action.
```

Sorry for the unclear initial post!

**Comment by Bogdanp** [comment]
Thanks for the additional details. So the issue really stems from trying to set up the broker before running the CLI code here, which is something I missed in your original post. Wouldn't moving the stuff inside `configure_broker` to the top level of another module and pointing the CLI to that resolve this or is the idea that you want to pass in more configuration in the call to `configure_broker` that you've elided from the example? If it's the latter case, then I'd say the recommended way to do stuff like that is to use env vars, but I know that's a lot less convenient than what you're trying to do here. I'll try to think about what a nice way to do this would be. I'm happy to take suggestions on what you think would be a useful interface here, too.

**Comment by rouge8** [comment]
> is the idea that you want to pass in more configuration in the call to configure_broker that you've elided from the example?

Exactly, yeah. The general flow of our app is `pyramid.paster.bootstrap("/path/to/config/file")` which calls `our_app.main()` which calls `our_app.configure_dramatiq()` which configures the broker, registers our actors, and etc. So a simplified version of our CLI is:

```python
def worker(config_file):
    pyramid.paster.bootstrap(config_file)  # triggers all of the configuration mentioned above

    command = [__name__]

    # Start the worker
    parser = make_argument_parser()
    args = parser.parse_args(command)
    dramatiq_worker(args)
```

> Wouldn't moving the stuff inside configure_broker to the top level of another module and pointing the CLI to that resolve this?

I hadn't thought about that! It's a little gross to have all of that done by importing the module, but that might be a reasonable workaround for now.

> I'm happy to take suggestions on what you think would be a useful interface here, too.

This is the roughly the startup code we had when we were evaluating Celery:

```python
from celery import Celery
from celery.signals import worker_init

@worker_init.connect
def _bootstrap_pyramid(signal, sender, **kwargs):
    import os
    import pyramid.paster
    import our_app

    ini_file = os.environ["INI"]

    # bootstrap pyramid settings and make accessible to celery app
    pyramid.paster.setup_logging(ini_file)
    env = pyramid.paster.bootstrap(ini_file)
    settings = env["registry"].settings

    # configure celery
    our_app.configure_celery(settings)

app = Celery("our_app")
```

That doesn't translate quite as nicely to Dramatiq because you can't really configure the broker after the fact. Maybe update the CLI to support calling a function that returns a broker? I don't think it needs to take any arguments; you could use env variables like we use `INI` or `DJANGO_SETTINGS_MODULE` to handle the configuration. Something like:

```console
$ dramatiq --help
usage: dramatiq [opts] broker_or_callable_returning_a_broker [module [module ...]]
```

```python
import os
import pyramid.paster

def configure_broker():
    ini_file = os.environ["INI"]
    pyramid.paster.setup_logging(ini_file)
    pyramid.paster.bootstrap(ini_file)  # calls our_app.main() which calls our_app.configure_dramatiq()
```

```console
$ INI=prod.ini dramatiq module:configure_broker
...  # dramatiq starts
```

What do you think?

**Comment by Bogdanp** [comment]
Thanks, that's what I was thinking, too. This should now be possible on master.

**Comment by rouge8** [comment]
This is perfect, thanks! (Sorry for the late reply, I was taking some time off)
