### ISSUE TITLE
waiting for group completion does not work if group is run from an actor

### ISSUE THREAD

**Issue by carsten-jahn** [Bogdanp/dramatiq#369]
It looks like waiting for all tasks of a group to finish works, if the group is created and waited for _outside_ the dramatiq actors. However, if an actor function creates a group and waits for its completion, not all group children are executed and the group never completes.

In detail: macOS 10.15.7 and dramatiq 1.9.0

### environment.yml for conda
```
name: dramatiq_test
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - 'dramatiq[rabbitmq, redis, watch]'
```

### docker-compose.yml
```
version: "2"

services:
  rabbitmq:
    command: rabbitmq-server --hostname dramatiqrabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
```

### broker.py
```
import dramatiq
from dramatiq.brokers.rabbitmq import RabbitmqBroker
from dramatiq.results.backends import RedisBackend
from dramatiq.results import Results

result_backend = RedisBackend()
rabbitmq_broker = RabbitmqBroker()
rabbitmq_broker.add_middleware(Results(backend=result_backend, store_results=True))
dramatiq.set_broker(rabbitmq_broker)
```

### tasks.py
```
import dramatiq
import logging
import time

from dramatiq import group

logging.basicConfig(
    format='%(asctime)s.%(msecs)03d %(process)d %(levelname)s %(name)s:%(lineno)d %(message)s',
    datefmt='%Y%m%d-%H%M%S',
    level=logging.DEBUG)

log = logging.getLogger(__name__)


@dramatiq.actor(max_retries=0, time_limit=30 * 60 * 1000, store_results=True)
def child_task(group_id: int, child_id:int):
    log.info('child_task start %s %s', group_id, child_id)
    time.sleep(2)
    log.info('child_task end   %s %s', group_id, child_id)


@dramatiq.actor(max_retries=0, time_limit=30 * 60 * 1000, store_results=True)
def group_task(group_id:int):
    log.info('group begin %s', group_id)
    # add children 1..5
    g = group([
        child_task.message(group_id, i) for i in range(1,6)
    ]).run()
    g.wait(timeout=1*60*1000)
    log.info('group end %s', group_id)
```

### cli.py
```
import logging
import sys
import broker
import tasks

logging.basicConfig(
    format='%(asctime)s.%(msecs)03d %(process)d %(levelname)s %(name)s:%(lineno)d %(message)s',
    datefmt='%Y%m%d-%H%M%S',
    level=logging.DEBUG)

log = logging.getLogger(__name__)

if __name__ == "__main__":
    tasks.group_task.send( int(sys.argv[1]))
```

### Running
```
dramatiq -v --processes 2 --threads 1  broker:rabbitmq_broker  tasks
python cli.py 1
```

### Actual Result
one of the five child_task are not processed and the group waits until timeout. Then, the remaining child_task gets processed.
```
(dramatiq_test) dramatiq_test $ dramatiq -v --processes 2 --threads 1  broker:rabbitmq_broker  tasks
[2020-12-14 10:29:44,782] [PID 40622] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.9.0' is booting up.
[2020-12-14 10:29:44,736] [PID 40625] [MainThread] [dramatiq.WorkerProcess(0)] [DEBUG] Loading broker...
[2020-12-14 10:29:44,765] [PID 40625] [MainThread] [dramatiq.middleware.prometheus.Prometheus] [DEBUG] Setting up metrics...
[2020-12-14 10:29:44,765] [PID 40625] [MainThread] [dramatiq.WorkerProcess(0)] [DEBUG] Loading modules...
[2020-12-14 10:29:44,766] [PID 40625] [MainThread] [dramatiq.WorkerProcess(0)] [DEBUG] Starting worker threads...
[2020-12-14 10:29:44,766] [PID 40625] [MainThread] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for queue 'default'.
[2020-12-14 10:29:44,766] [PID 40625] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Running consumer thread...
[2020-12-14 10:29:44,766] [PID 40625] [MainThread] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for delay queue 'default.DQ'.
[2020-12-14 10:29:44,766] [PID 40625] [Thread-3] [dramatiq.worker.ConsumerThread(default.DQ)] [DEBUG] Running consumer thread...
[2020-12-14 10:29:44,766] [PID 40625] [Thread-3] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for queue 'default.DQ'.
[2020-12-14 10:29:44,766] [PID 40625] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Running worker thread...
[2020-12-14 10:29:44,767] [PID 40625] [Thread-3] [dramatiq.worker.Worker] [DEBUG] A consumer for queue 'default.DQ' is already running.
[2020-12-14 10:29:44,767] [PID 40625] [Thread-3] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for delay queue 'default.DQ'.
[2020-12-14 10:29:44,767] [PID 40625] [Thread-3] [dramatiq.worker.Worker] [DEBUG] A consumer for queue 'default.DQ' is already running.
[2020-12-14 10:29:44,779] [PID 40625] [MainThread] [dramatiq.WorkerProcess(0)] [INFO] Worker process is ready for action.
[2020-12-14 10:29:44,736] [PID 40626] [MainThread] [dramatiq.WorkerProcess(1)] [DEBUG] Loading broker...
[2020-12-14 10:29:44,765] [PID 40626] [MainThread] [dramatiq.middleware.prometheus.Prometheus] [DEBUG] Setting up metrics...
[2020-12-14 10:29:44,765] [PID 40626] [MainThread] [dramatiq.WorkerProcess(1)] [DEBUG] Loading modules...
[2020-12-14 10:29:44,765] [PID 40626] [MainThread] [dramatiq.WorkerProcess(1)] [DEBUG] Sending forks to main process...
[2020-12-14 10:29:44,766] [PID 40626] [MainThread] [dramatiq.WorkerProcess(1)] [DEBUG] Starting worker threads...
[2020-12-14 10:29:44,766] [PID 40626] [MainThread] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for queue 'default'.
[2020-12-14 10:29:44,766] [PID 40626] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Running consumer thread...
[2020-12-14 10:29:44,766] [PID 40626] [MainThread] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for delay queue 'default.DQ'.
[2020-12-14 10:29:44,766] [PID 40626] [Thread-3] [dramatiq.worker.ConsumerThread(default.DQ)] [DEBUG] Running consumer thread...
[2020-12-14 10:29:44,766] [PID 40626] [Thread-3] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for queue 'default.DQ'.
[2020-12-14 10:29:44,766] [PID 40626] [Thread-3] [dramatiq.worker.Worker] [DEBUG] A consumer for queue 'default.DQ' is already running.
[2020-12-14 10:29:44,766] [PID 40626] [Thread-3] [dramatiq.worker._WorkerMiddleware] [DEBUG] Adding consumer for delay queue 'default.DQ'.
[2020-12-14 10:29:44,766] [PID 40626] [Thread-3] [dramatiq.worker.Worker] [DEBUG] A consumer for queue 'default.DQ' is already running.
[2020-12-14 10:29:44,767] [PID 40626] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Running worker thread...
[2020-12-14 10:29:44,767] [PID 40626] [MainThread] [dramatiq.WorkerProcess(1)] [INFO] Worker process is ready for action.
[2020-12-14 10:29:44,947] [PID 40629] [MainThread] [dramatiq.ForkProcess(0)] [DEBUG] Loading fork function...
[2020-12-14 10:29:44,947] [PID 40629] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Fork process 'dramatiq.middleware.prometheus:_run_exposition_server' is ready for action.
[2020-12-14 10:29:44,947] [PID 40629] [MainThread] [dramatiq.middleware.prometheus._run_exposition_server] [DEBUG] Starting exposition server...
[2020-12-14 10:29:56,045] [PID 40625] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Pushing message 'cc6d18d8-39b7-4821-874a-a33f3fb752c0' onto work queue.
[2020-12-14 10:29:56,046] [PID 40625] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Received message group_task(1) with id 'cc6d18d8-39b7-4821-874a-a33f3fb752c0'.
[2020-12-14 10:29:56,055] [PID 40625] [Thread-4] [tasks.group_task] [DEBUG] Received args=(1,) kwargs={}.
[2020-12-14 10:29:56,056] [PID 40625] [Thread-4] [tasks] [INFO] group begin 1
[2020-12-14 10:29:56,056] [PID 40625] [Thread-4] [dramatiq.broker.RabbitmqBroker] [DEBUG] Enqueueing message '43a3fdf6-1139-413a-b48d-dc6b37ff33c8' on queue 'default'.
[2020-12-14 10:29:56,076] [PID 40625] [Thread-4] [dramatiq.broker.RabbitmqBroker] [DEBUG] Enqueueing message '12e822e6-fa1f-4b39-8a38-902bbddef80e' on queue 'default'.
[2020-12-14 10:29:56,077] [PID 40625] [Thread-4] [dramatiq.broker.RabbitmqBroker] [DEBUG] Enqueueing message '8c309c67-f8d2-413d-b123-c63d5e18ff20' on queue 'default'.
[2020-12-14 10:29:56,077] [PID 40625] [Thread-4] [dramatiq.broker.RabbitmqBroker] [DEBUG] Enqueueing message 'e8b5385c-f4c9-40d1-b2a5-222571e5887c' on queue 'default'.
[2020-12-14 10:29:56,078] [PID 40625] [Thread-4] [dramatiq.broker.RabbitmqBroker] [DEBUG] Enqueueing message 'cf2d4f4b-c364-4bc3-bdff-828c8add79fe' on queue 'default'.
[2020-12-14 10:29:56,081] [PID 40626] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Pushing message '43a3fdf6-1139-413a-b48d-dc6b37ff33c8' onto work queue.
[2020-12-14 10:29:56,082] [PID 40626] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Received message child_task(1, 1) with id '43a3fdf6-1139-413a-b48d-dc6b37ff33c8'.
[2020-12-14 10:29:56,083] [PID 40625] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Pushing message '12e822e6-fa1f-4b39-8a38-902bbddef80e' onto work queue.
[2020-12-14 10:29:56,088] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Received args=(1, 1) kwargs={}.
[2020-12-14 10:29:56,089] [PID 40626] [Thread-4] [tasks] [INFO] child_task start 1 1
[2020-12-14 10:29:56,089] [PID 40626] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Pushing message '8c309c67-f8d2-413d-b123-c63d5e18ff20' onto work queue.
[2020-12-14 10:29:58,093] [PID 40626] [Thread-4] [tasks] [INFO] child_task end   1 1
[2020-12-14 10:29:58,093] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Completed after 2004.74ms.
[2020-12-14 10:29:58,144] [PID 40626] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Acknowledging message '43a3fdf6-1139-413a-b48d-dc6b37ff33c8'.
[2020-12-14 10:29:58,145] [PID 40626] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Received message child_task(1, 3) with id '8c309c67-f8d2-413d-b123-c63d5e18ff20'.
[2020-12-14 10:29:58,145] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Received args=(1, 3) kwargs={}.
[2020-12-14 10:29:58,145] [PID 40626] [Thread-4] [tasks] [INFO] child_task start 1 3
[2020-12-14 10:29:58,150] [PID 40626] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Pushing message 'e8b5385c-f4c9-40d1-b2a5-222571e5887c' onto work queue.
[2020-12-14 10:30:00,145] [PID 40626] [Thread-4] [tasks] [INFO] child_task end   1 3
[2020-12-14 10:30:00,146] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Completed after 2000.81ms.
[2020-12-14 10:30:00,150] [PID 40626] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Acknowledging message '8c309c67-f8d2-413d-b123-c63d5e18ff20'.
[2020-12-14 10:30:00,151] [PID 40626] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Received message child_task(1, 4) with id 'e8b5385c-f4c9-40d1-b2a5-222571e5887c'.
[2020-12-14 10:30:00,151] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Received args=(1, 4) kwargs={}.
[2020-12-14 10:30:00,151] [PID 40626] [Thread-4] [tasks] [INFO] child_task start 1 4
[2020-12-14 10:30:00,157] [PID 40626] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Pushing message 'cf2d4f4b-c364-4bc3-bdff-828c8add79fe' onto work queue.
[2020-12-14 10:30:02,152] [PID 40626] [Thread-4] [tasks] [INFO] child_task end   1 4
[2020-12-14 10:30:02,152] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Completed after 2001.33ms.
[2020-12-14 10:30:02,161] [PID 40626] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Acknowledging message 'e8b5385c-f4c9-40d1-b2a5-222571e5887c'.
[2020-12-14 10:30:02,161] [PID 40626] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Received message child_task(1, 5) with id 'cf2d4f4b-c364-4bc3-bdff-828c8add79fe'.
[2020-12-14 10:30:02,162] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Received args=(1, 5) kwargs={}.
[2020-12-14 10:30:02,162] [PID 40626] [Thread-4] [tasks] [INFO] child_task start 1 5
[2020-12-14 10:30:04,165] [PID 40626] [Thread-4] [tasks] [INFO] child_task end   1 5
[2020-12-14 10:30:04,165] [PID 40626] [Thread-4] [tasks.child_task] [DEBUG] Completed after 2003.38ms.
[2020-12-14 10:30:04,169] [PID 40626] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Acknowledging message 'cf2d4f4b-c364-4bc3-bdff-828c8add79fe'.
[2020-12-14 10:30:55,212] [PID 40625] [Thread-4] [tasks.group_task] [DEBUG] Completed after 59155.75ms.
[2020-12-14 10:30:55,213] [PID 40625] [Thread-4] [dramatiq.worker.WorkerThread] [ERROR] Failed to process message group_task(1) with unhandled exception.
Traceback (most recent call last):
  File "/Users/u/tools/miniconda3/envs/dramatiq_test/lib/python3.8/site-packages/dramatiq/worker.py", line 470, in process_message
    res = actor(*message.args, **message.kwargs)
  File "/Users/u/tools/miniconda3/envs/dramatiq_test/lib/python3.8/site-packages/dramatiq/actor.py", line 145, in __call__
    result = self.fn(*args, **kwargs)
  File "./tasks.py", line 29, in group_task
    g.wait(timeout=1*60*1000)
  File "/Users/u/tools/miniconda3/envs/dramatiq_test/lib/python3.8/site-packages/dramatiq/composition.py", line 337, in wait
    for _ in self.get_results(block=True, timeout=timeout):  # pragma: no cover
  File "/Users/u/tools/miniconda3/envs/dramatiq_test/lib/python3.8/site-packages/dramatiq/composition.py", line 327, in get_results
    yield child.get_result(block=block, timeout=timeout)
  File "/Users/u/tools/miniconda3/envs/dramatiq_test/lib/python3.8/site-packages/dramatiq/message.py", line 147, in get_result
    return backend.get_result(self, block=block, timeout=timeout)
  File "/Users/u/tools/miniconda3/envs/dramatiq_test/lib/python3.8/site-packages/dramatiq/results/backends/redis.py", line 82, in get_result
    raise ResultTimeout(message)
dramatiq.results.errors.ResultTimeout: child_task(1, 2)
[2020-12-14 10:30:55,217] [PID 40625] [Thread-4] [dramatiq.middleware.retries.Retries] [WARNING] Retries exceeded for message 'cc6d18d8-39b7-4821-874a-a33f3fb752c0'.
[2020-12-14 10:30:55,234] [PID 40625] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Rejecting message 'cc6d18d8-39b7-4821-874a-a33f3fb752c0'.
[2020-12-14 10:30:55,237] [PID 40625] [Thread-4] [dramatiq.worker.WorkerThread] [DEBUG] Received message child_task(1, 2) with id '12e822e6-fa1f-4b39-8a38-902bbddef80e'.
[2020-12-14 10:30:55,237] [PID 40625] [Thread-4] [tasks.child_task] [DEBUG] Received args=(1, 2) kwargs={}.
[2020-12-14 10:30:55,237] [PID 40625] [Thread-4] [tasks] [INFO] child_task start 1 2
[2020-12-14 10:30:57,241] [PID 40625] [Thread-4] [tasks] [INFO] child_task end   1 2
[2020-12-14 10:30:57,241] [PID 40625] [Thread-4] [tasks.child_task] [DEBUG] Completed after 2003.69ms.
[2020-12-14 10:30:57,244] [PID 40625] [Thread-4] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Acknowledging message '12e822e6-fa1f-4b39-8a38-902bbddef80e'.
```

### Expected Result
I'd like to see "child_task start 1 2" earlier, among the other four tasks, and group_task finishing without exception so it prints the "group end" log.

### Variation with group greation in cli.py
If ".send" is omitted, in cli.py (so the line reads `tasks.group_task( int(sys.argv[1]))` ), the group task is not run in a dramatiq worker but in cli.py. There it creates its group of five child_task and waits for it. This works fine. However, what I would like to do, is being able to wait for some things to finish inside a dramatiq actor.

The docs around groups and pipelines don't say that any restrictions exist. And the pipelines docs suggest  that actors can pass results to each other. The group abstraction is also based on results. 

### Variation with multiple threads instead of processes
If I run the worker like this:
```
dramatiq -v --processes 1 --threads 2  broker:rabbitmq_broker  tasks
```
and use "send" in cli.py as in the full code example above, it also works fine. Also multiple processes with multiple threads work.

I hope there is a mistake on my side, but it looks like a bug to me. Thanks for looking into this!

**Comment by Bogdanp** [comment]
You're experiencing worker starvation. You're running a single worker thread per process so what happens is the job is pulled on the same worker where the actor is waiting for the group to finish. Because an actor is already running on that thread, the other actor can't run until the first one times out. You should either ensure you always have enough resources to process the max group size + 1 (though still not a good idea in general), or re-structure your topology to avoid starvation (eg. run different sets of workers for the actors that wait and for the actors that perform the grouped work), or configure the workers to disable preloading (not recommended because it limits your throughput).

**Comment by carsten-jahn** [comment]
Thanks so much for explaining this. Now I realize there were similar cases discussed but it did not occur to me before. Since throughput is not an issue for me, I'm defining the environment variable `dramatiq_queue_prefetch=1` and indeed this resolves my issue.
