### ISSUE TITLE
Running all files in a folder with cli

### ISSUE THREAD

**Issue by kgrvamsi** [Bogdanp/dramatiq#374]
## What OS are you using?

Ubuntu 16.04

## What version of Dramatiq are you using?

1.9.0

## What did you do?

dramatiq queues/* -p 1

## What did you expect would happen?

To run every file  inside the folder

## What happened?

```bash
$ls -hl queues/
total 4.0K
-rw-r--r-- 1 root root 488 Jan  6 18:11 testing_queue.py

$ dramatiq queues/* -p 1
[2021-01-06 20:10:43,838] [PID 19148] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.9.0' is booting up.
[2021-01-06 20:10:43,839] [PID 19148] [MainThread] [dramatiq.MainProcess] [CRITICAL] Worker with PID 19151 exited unexpectedly (code 2). Shutting down...
[2021-01-06 20:10:42,836] [PID 19151] [MainThread] [dramatiq.WorkerProcess(0)] [ERROR] Failed to import module.
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.8/site-packages/dramatiq/cli.py", line 330, in worker_process
    module, broker = import_broker(args.broker)
  File "/home/vagrant/venv/lib/python3.8/site-packages/dramatiq/cli.py", line 120, in import_broker
    module, broker = import_object(value)
  File "/home/vagrant/venv/lib/python3.8/site-packages/dramatiq/cli.py", line 109, in import_object
    module = importlib.import_module(modname)
  File "/home/vagrant/venv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'queues/testing_queue'
```

testing_queue.py file contains the following code

```python
import dramatiq

@dramatiq.actor(queue_name='default')
def testing_queue1():
        print("Hello World")
```

**Comment by Bogdanp** [comment]
Dramatiq expects module import paths as its arguments. You probably want something along these lines (untested)

```sh
for mod in queues/*.py; do printf "queues.%s\n" $(basename ${mod//.py/}); done | xargs dramatiq -p1 
```

**Comment by kgrvamsi** [comment]
Thanks @Bogdanp this worked !!!
