### ISSUE TITLE
get_current_message always return None

### ISSUE THREAD

**Issue by notwhy** [Bogdanp/dramatiq#398]
# Issues

get_current_message always return None

## What OS are you using?

macOS 

## What version of Dramatiq are you using?

1.10.0

## What did you do?
for example
```
@dramatiq.actor(queue_name='test')
def example(x):
    logging.debug(111)
    logging.debug(CurrentMessage)
    logging.debug(CurrentMessage.get_current_message())
    logging.debug(CurrentMessage.get_current_message()._message)
    logging.debug(222)

 dramatiq-gevent --threads 1 --processes 1 test -Q test
```
then i run 
```example.send(111)```
i got message
2021-04-28 11:44:58 mac broker[71804] DEBUG 111
2021-04-28 11:44:58 mac broker[71804] DEBUG <class 'dramatiq.middleware.current_message.CurrentMessage'>
2021-04-28 11:44:58 mac broker[71804] DEBUG None
2021-04-28 11:44:58 mac test.example[71804] DEBUG Completed after 0.88ms.
2021-04-28 11:44:58 mac dramatiq.worker.WorkerThread[71804] ERROR Failed to process message example(111) with unhandled exception.
Traceback (most recent call last):
  File "/Users/whynot/python/scanner3/venv/lib/python3.8/site-packages/dramatiq/worker.py", line 476, in process_message
    res = actor(*message.args, **message.kwargs)
  File "/Users/whynot/python/scanner3/venv/lib/python3.8/site-packages/dramatiq/actor.py", line 145, in __call__
    return self.fn(*args, **kwargs)
  File "./test.py", line 21, in example
    logging.debug(CurrentMessage.get_current_message()._message)
AttributeError: 'NoneType' object has no attribute '_message'
2021-04-28 11:44:58 mac max_tasks_per_child.app.MaxTasksPerChild[71804] 

## What did you expect would happen?
print something like follow
Message(queue_name='default', actor_name='accessor', args=(1,), kwargs={}, options={}, message_id='3e385358-3f0f-482a-8ab7-b3a75521992d', message_timestamp=1619580622420)

## What happened?

it return None.

I saw the pytest test_currrent_message_middleware_exposes_the_current_message method, it works with the     stub_broker.join(accessor.queue_name)
But How can i get message in an @dramatiq.actor realtime

**Comment by Bogdanp** [comment]
The current message middleware is not amongst the default set of middleware, so to get it to work you need to add it (eg. `dramatiq.get_broker().add_middleware(CurrentMessage())`.

**Comment by notwhy** [comment]
Thanks a lot . it solved my problem.
