### ISSUE TITLE
Python 3.10 AttributeError on boot up

### ISSUE THREAD

**Issue by codingjoe** [Bogdanp/dramatiq#432]
# Issues

We tried running dramatiq on Python 3.10 and ran into a AttributeError.

I am aware that this package might not be 3.10 compatible yet, but I figured I leave you the stack trace to make your life easier. Great package btw, love the work you are doing here!

## What OS are you using?

Ubuntu 20 (heroku-20 docker image)

## What version of Dramatiq are you using?

1.11.0

## What did you do?

Start the worker.

## What did you expect would happen?

It to run ;)

## What happened?

```
Traceback (most recent call last):
   File "/app/.heroku/python/bin/dramatiq", line 5, in <module>
     from dramatiq.__main__ import main
   File "/app/.heroku/python/lib/python3.10/site-packages/dramatiq/__main__.py", line 20, in <module>
     from dramatiq.cli import main
   File "/app/.heroku/python/lib/python3.10/site-packages/dramatiq/cli.py", line 40, in <module>
     from .watcher import setup_file_watcher
   File "/app/.heroku/python/lib/python3.10/site-packages/dramatiq/watcher.py", line 6, in <module>
     import watchdog.observers.polling
   File "/app/.heroku/python/lib/python3.10/site-packages/watchdog/observers/__init__.py", line 63, in <module>
     from .inotify import InotifyObserver as Observer
   File "/app/.heroku/python/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 76, in <module>
    from watchdog.observers.api import (
   File "/app/.heroku/python/lib/python3.10/site-packages/watchdog/observers/api.py", line 23, in <module>
     from watchdog.utils.bricks import SkipRepeatsQueue
   File "/app/.heroku/python/lib/python3.10/site-packages/watchdog/utils/bricks.py", line 175, in <module>
     class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

**Comment by Bogdanp** [comment]
Good to know, thanks!
