### ISSUE TITLE
AttributeError when consuming using Redis broker

### ISSUE THREAD

**Issue by tiwilliam** [Bogdanp/dramatiq#459]
# Issues

## Checklist

* [x] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?
macOS 11.6
redis 6.2

## What version of Dramatiq are you using?
1.12.1

## What did you do?

Added a single message to the default queue and consumed it using a Redis broker. Consumer started with:
```
dramatiq backend.tasks --watch backend --verbose
```

## What did you expect would happen?

Acknowledge the message and continue polling without any error or restarted worker threads.

## What happened?

Unhandled `None` return from `do_fetch` when using the Redis broker. This seems to be a race-condition when acknowledging and fetching at the same time. I've added some debug printing on line 382 in `brokers.redis` to show the return value when this happens.
```
[2021-12-28 12:47:16,964] [PID 47696] [Thread-5] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Acknowledging message '0c207892-8413-4ff4-b84c-842bb2e8380e'.
self.broker.do_fetch: default 15 => None
self.broker.do_fetch: default 16 => []
[2021-12-28 12:47:17,010] [PID 47696] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [CRITICAL] Consumer encountered an unexpected error.
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/3.10.0/virtualenvs/backend/lib/python3.10/site-packages/dramatiq/worker.py", line 264, in run
    for message in self.consumer:
  File "/Users/william/.pyenv/versions/3.10.0/virtualenvs/backend/lib/python3.10/site-packages/dramatiq/brokers/redis.py", line 346, in __next__
    data = self.message_cache.pop(0)
AttributeError: 'NoneType' object has no attribute 'pop'
```

Some more printing on what's passed to LUA:
```
[2021-12-28 14:30:51,217] [PID 51481] [Thread-2] [dramatiq.broker.RedisBroker] [WARNING] dispatch: ['dramatiq'] , ['fetch', 1640698251217, 'default', 'b5566044-2124-4e28-a685-a9a9bdf74559', 60000, 604800000, 0, 3996, 15]
[2021-12-28 14:30:51,223] [PID 51481] [Thread-2] [dramatiq.brokers.redis._RedisConsumer] [WARNING] messages: []
[2021-12-28 14:30:51,275] [PID 51481] [Thread-7] [backend.tasks.send_email] [DEBUG] Completed after 144.20ms.
[2021-12-28 14:30:51,285] [PID 51481] [Thread-7] [dramatiq.worker.ConsumerThread(default)] [DEBUG] Acknowledging message '82500a7c-153c-4068-aa3b-95c716719408'.
[2021-12-28 14:30:51,285] [PID 51481] [Thread-7] [dramatiq.broker.RedisBroker] [WARNING] dispatch: ['dramatiq'] , ['ack', 1640698251285, 'default', 'b5566044-2124-4e28-a685-a9a9bdf74559', 60000, 604800000, 0, 3996, '2e32b464-33e8-4ca3-9d93-cf0de95b91b4']
[2021-12-28 14:30:51,287] [PID 51481] [Thread-2] [dramatiq.broker.RedisBroker] [WARNING] dispatch: ['dramatiq'] , ['fetch', 1640698251287, 'default', 'b5566044-2124-4e28-a685-a9a9bdf74559', 60000, 604800000, 0, 3996, 15]
[2021-12-28 14:30:51,288] [PID 51481] [Thread-2] [dramatiq.brokers.redis._RedisConsumer] [WARNING] messages: None
[2021-12-28 14:30:51,376] [PID 51481] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [CRITICAL] Consumer encountered an unexpected error.
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/3.10.0/virtualenvs/backend/lib/python3.10/site-packages/dramatiq/worker.py", line 264, in run
    for message in self.consumer:
  File "/Users/william/.pyenv/versions/3.10.0/virtualenvs/backend/lib/python3.10/site-packages/dramatiq/brokers/redis.py", line 360, in __next__
    data = self.message_cache.pop(0)
AttributeError: 'NoneType' object has no attribute 'pop'
[2021-12-28 14:30:51,378] [PID 51481] [Thread-2] [dramatiq.worker.ConsumerThread(default)] [INFO] Restarting consumer in 3.00 seconds.
[2021-12-28 14:30:51,394] [PID 51483] [Thread-2] [dramatiq.broker.RedisBroker] [WARNING] dispatch: ['dramatiq'] , ['fetch', 1640698251394, 'default', '8ecf63db-b093-463f-a73d-ef4c3071d9eb', 60000, 604800000, 0, 3996, 16]
[2021-12-28 14:30:51,398] [PID 51483] [Thread-2] [dramatiq.brokers.redis._RedisConsumer] [WARNING] messages: []
```

**Comment by tiwilliam** [comment]
I've attached a PR where I introduced a lock which seem to resolve this issue. See Bogdanp/dramatiq#460.

**Comment by Bogdanp** [comment]
Sorry @tiwilliam, I haven't had a chance to look at this yet. The dispatch functions already run single-threaded within Redis, so I don't think adding a lock is the right solution here. I'll try to take a look this weekend.

The detail about using a single-connection pool helps.
