### ISSUE TITLE
Use SCAN or the like instead of KEYS

### ISSUE THREAD

**Issue by Stealthmate** [Bogdanp/dramatiq#491]
## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do? Deploy to production
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

`python:3.9-alpine`

## What version of Dramatiq are you using?

1.12.3

## What did you do?

Deploy to production

## What did you expect would happen?

Nothing

## What happened?

My Redis provider blocks `KEYS` because it's slow (as described in the [redis docs](https://redis.io/commands/keys/)), so I got an error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dramatiq/brokers/redis.py", line 346, in __next__
    data = self.message_cache.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dramatiq/worker.py", line 264, in run
    for message in self.consumer:
  File "/usr/local/lib/python3.9/site-packages/dramatiq/brokers/redis.py", line 365, in __next__
    self.message_cache = messages = self.broker.do_fetch(
  File "/usr/local/lib/python3.9/site-packages/dramatiq/brokers/redis.py", line 283, in do_dispatch
    return dispatch(args=args, keys=keys)
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 5704, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 5089, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 5073, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1235, in execute_command
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1236, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1212, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1251, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 837, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_1b0bca8bf4560c1f4a84ff992da836e49515f830): @user_script:128: @user_script: 128: Unknown Redis command called from Lua script
```

Looking at line 128 in `dispatch.lua`:
```
local ack_queues = redis.call("keys", dead_worker_acks .. "*")
```

lead me to believe that `KEYS` might be blocked and when I tried it via the redis cli, it complained about unknown command. On the flip side, dramatiq works fine on my local redis container.

I don't know if `dramatiq` would have any problems with using something other than `KEYS`, but this is a blocker for me so I'm probably gonna fork it and change the lua script to use `SCAN` instead. Would be happy to open a PR later :)

**Comment by Bogdanp** [comment]
I'd be happy to merge a change to use `SCAN` instead, assuming it doesn't slow things down or significantly complicate the code.

**Comment by zclaiqcc** [comment]
When would related PR be merged?
