### ISSUE TITLE
Beginners ask for help

### ISSUE THREAD

**Issue by singdoo** [Bogdanp/dramatiq#535]
```import requests
import dramatiq
from tqdm import tqdm
import json

# Set up Dramatiq
dramatiq.set_broker("amqp://root:123456@localhost:5672")
dramatiq.set_encoder(json.JSONEncoder())

# head_request Task
@dramatiq.actor(max_retries=3)
def head_request(url, success_file, error_file):
    try:
        r = requests.head(url.strip())
        if r.status_code == 200:
            with open(success_file, "a") as f:
                f.write(url)
        else:
            with open(error_file, "a") as f:
                f.write(url)
    except:
        head_request.send_with_options(args=(url, success_file, error_file), delay=1000)

# Split my example
def split_file(file_path, splits):
    total_lines = sum(1 for line in open(file_path))
    with open(file_path) as f:
        for i in range(0, total_lines, splits):
            opath = '{}.{}'.format(file_path, i)
            with open(opath, 'w') as fout:
                for line in tqdm(list(f)[i:i+splits], desc=opath, total=splits):
                    fout.write(line)
                    
# Execute the splitting
split_file('url.txt',2000)

# Perform the requests using Dramatiq
from glob import glob

URLS_PER_CHUNK = 2000
SPLITS = glob('url.txt*')
success_file = '200.txt'
error_file = 'error.txt'
for split in SPLITS:
    with open(success_file, 'a') as f:
        f.write('')  # create file if it doesn't exist
    with open(error_file, 'a') as f:
        f.write('')  # create file if it doesn't exist
    urls = open(split).readlines()
    tasks = [head_request.send(url.strip(), success_file, error_file) for url in urls]
    for chunk_begin in range(0, len(tasks), URLS_PER_CHUNK):
        dramatiq.group(tasks[chunk_begin:chunk_begin+URLS_PER_CHUNK]).run()
        print("processed chunk {}/{}".format(chunk_begin//URLS_PER_CHUNK, len(tasks)//URLS_PER_CHUNK))
```

=========================================================================

[root@localhost cao]# dramatiq --threads 10 t.py
[2023-03-04 00:52:07,489] [PID 4613] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.14.1' is booting up.
[2023-03-04 00:52:07,490] [PID 4613] [MainThread] [dramatiq.MainProcess] [CRITICAL] Worker with PID 4614 exited unexpectedly (code 1). Shutting down...
Process Process-1:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/dramatiq/cli.py", line 382, in worker_process
    module, broker = import_broker(args.broker)
  File "/root/miniconda3/lib/python3.9/site-packages/dramatiq/cli.py", line 123, in import_broker
    module, broker_or_callable = import_object(value)
  File "/root/miniconda3/lib/python3.9/site-packages/dramatiq/cli.py", line 112, in import_object
    module = importlib.import_module(modname)
  File "/root/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/cao/./t.py", line 12, in <module>
    def head_request(url, success_file, error_file):
  File "/root/miniconda3/lib/python3.9/site-packages/dramatiq/actor.py", line 261, in decorator
    invalid_options = set(options) - broker.actor_options
AttributeError: 'str' object has no attribute 'actor_options'

(base) [root@localhost cao]# pip list | grep dramatiq
dramatiq               1.14.1
(base) [root@localhost cao]# rpm -qa | grep rabbitmq-server
rabbitmq-server-3.8.26-1.el7.noarch

**Comment by singdoo** [comment]
Dramatiq Why are you so unfriendly to beginners? 
The questions asked have not been answered, whether on this forum or in github
