### ISSUE TITLE
Dramatiq workers hangs after very often, no logs were seen in logs even if it is verbose mode.

### ISSUE THREAD

**Issue by Harinib-Kore** [Bogdanp/dramatiq#578]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [mailing list](https://groups.io/g/dramatiq-users/topics).

## Checklist

* [ ] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [ ] What OS are you using?
* [ ] What version of Dramatiq are you using?
* [ ] What did you do?
* [ ] What did you expect would happen?
* [ ] What happened?

## What OS are you using?

Centos

## What version of Dramatiq are you using?

Dramatiq version 1.14.2

## What did you do?

Processing parallel async requests using dramatiq

## What did you expect would happen?

It should work properly it should receive messages and tasks, but it is getting hanged. 

## What happened?

We are processing parallel async requests. It will work fine for 3 days and again the same issue occurs. If we restart the workers then it works , how to fix this

**dramatiq dramatiq_app.BatchOperationsDramatiqTasks --processes 1 --verbose**

I cant see anything in logs files. Even logs getting hanged

**Comment by spumer** [comment]
We got something similiar with --process 1 --threads 2. When Worker consume one queue and produce messages to another.
We reproduce it yesterday and will investigate what happend actually

**Comment by Alsheh** [comment]
I've observed similar behavior when the CPU reaches 100%.

**Comment by menezes-** [comment]
I have the same issue with 1.15 using the AsyncIO middleware. Trying to figure out what part of the code is hanging. 

using `--process 1 --threads 1 ` works

**Comment by agamrp** [comment]
I am seeing this as well running with `--processes 4 --threads 1` running through `django_dramatiq`
I'll try updating to 1 process and see how that goes.

**Comment by spumer** [comment]
I'm released thread-safe broker implemention ohttps://github.com/spumer/dramatiq-kombu-broker/
We does not have hangs anymore with that

**Comment by Harinib-Kore** [comment]
> I'm released thread-safe broker implemention https://github.com/spumer/dramatiq-kombu-broker/ We does not have hangs anymore with that

hey what combination work wells whether it is dramatiq kombu broker and redis as backend ,
or should i use both kombu

**Comment by spumer** [comment]
Works well with `kombu + rabbitmq`

**Comment by Harinib-Kore** [comment]
Is there a way to check the current status of a Dramatiq task by its jobId? Specifically, to determine if it is still running or has completed? Also, is it possible to assign a custom name to the job, similar to a functionality available in Celery?

In Celery, you can achieve this with the following code:

```python
celery_task = celery.AsyncResult(id=job_id, app=celery)
if celery_task.state != 'REVOKED':
```

My primary intention is to manage long-running tasks by being able to terminate them if necessary. How can I remove such tasks from the queue in Dramatiq?

**Comment by spumer** [comment]
>Is there a way to check the current status of a Dramatiq task by its jobId? 

We solve it by https://github.com/Bogdanp/django_dramatiq, it has Task model and middleware which write message status

>Also, is it possible to assign a custom name to the job, similar to a functionality available in Celery?

You mean `display_name` in Celery? Where you expect to see that in Dramatiq? :) I think Actor name is enough

**Comment by Harinib-Kore** [comment]
> > Is there a way to check the current status of a Dramatiq task by its jobId?
> 
> We solve it by https://github.com/Bogdanp/django_dramatiq, it has Task model and middleware which write message status
> 
> > Also, is it possible to assign a custom name to the job, similar to a functionality available in Celery?
> 
> You mean `display_name` in Celery? Where you expect to see that in Dramatiq? :) I think Actor name is enough

how to get process id of task  with message id or any other parameter in dramatiq ?

**Comment by spumer** [comment]
You need to implement manually. Dramatiq has no functionality to revoke task.

I think it can be done by implement like in celery: create queue for events and dispatch events by worker when done some action and listen for any other. Then you can implement "revoke event", and discard message when worker receive it

**Comment by Harinib-Kore** [comment]
Hi i am facing issue , can you tell me how to solve this

{
name: 'CrawlerDramatiq',
script: '/bin/bash',
args: "-c 'cd /data/www/Findly/search && source /data/sa_py3.9.7/Findly/bin/activate && dramatiq dramatiq_app.CrawlDramatiqTasks --processes 4'",
autorestart: true,
log_file : "/data/logs/findly/crawler_dramatiq.log",
watch: false
},

Exception in thread Thread-1:
Traceback (most recent call last):
File "/data/sa_py3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/data/sa_py3.9.7/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/data/sa_py3.9.7/Findly/lib/python3.9/site-packages/dramatiq/cli.py", line 337, in watch_logs
log_file.write(data + "\n")
MemoryError

i am getting this how to resolve this
