### ISSUE TITLE
Error when running async actor with AsyncIO middleware

### ISSUE THREAD

**Issue by guedesfelipe** [Bogdanp/dramatiq#643]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [mailing list](https://groups.io/g/dramatiq-users/topics).

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Ubuntu 20.04

## What version of Dramatiq are you using?

1.17.0

## What did you do?

Adding AsyncIO middleware:

```py
import dramatiq
from dramatiq.brokers.rabbitmq import RabbitmqBroker
from dramatiq.middleware import AsyncIO


rabbitmq_broker = RabbitmqBroker(url="amqp://guest:guest@127.0.0.1:5672")
dramatiq.set_broker(rabbitmq_broker)
rabbitmq_broker.add_middleware(AsyncIO)


@dramatiq.actor()
async def dramatiq_test(data):
    print(data)

```

Running:
`dramatiq main`

## What did you expect would happen?

Run async actor

## What happened?

Error:

```sh

[2024-07-19 14:15:42,763] [PID 261184] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.17.0' is booting up.
Process Process-1:
Traceback (most recent call last):
  File "/home/felipeguedes/.asdf/installs/python/3.10.12/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/felipeguedes/.asdf/installs/python/3.10.12/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/async_dramatiq/.venv/lib/python3.10/site-packages/dramatiq/cli.py", line 393, in worker_process
    module, broker = import_broker(args.broker)
  File "/tmp/async_dramatiq/.venv/lib/python3.10/site-packages/dramatiq/cli.py", line 123, in import_broker
    module, broker_or_callable = import_object(value)
  File "/tmp/async_dramatiq/.venv/lib/python3.10/site-packages/dramatiq/cli.py", line 112, in import_object
    module = importlib.import_module(modname)
  File "/home/felipeguedes/.asdf/installs/python/3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/async_dramatiq/./async_dramatiq/main.py", line 8, in <module>
    rabbitmq_broker.add_middleware(AsyncIO)
  File "/tmp/async_dramatiq/.venv/lib/python3.10/site-packages/dramatiq/broker.py", line 152, in add_middleware
    self.actor_options |= middleware.actor_options
TypeError: unsupported operand type(s) for |=: 'set' and 'property'
```

**Comment by guedesfelipe** [comment]
Replace: 
```py
rabbitmq_broker.add_middleware(AsyncIO)
```
To:
```py
rabbitmq_broker.add_middleware(AsyncIO())
```
