### ISSUE TITLE
Getting dramatiq.errors.ConnectionClosed when using example code from website

### ISSUE THREAD

**Issue by kiorq** [Bogdanp/dramatiq#85]
Using this example code i got from the home page
```python
import dramatiq
import requests

@dramatiq.actor
def count_words(url):
   response = requests.get(url)
   count = len(response.text.split(" "))
   print(f"There are {count} words at {url!r}.")

# Synchronously count the words on example.com in the current process
count_words("http://example.com")

# or send the actor a message so that it may perform the count
# later, in a separate process.
count_words.send("http://example.com")
```

When i run 
`dramatiq middleman`

I get this:
```
[2018-05-03 10:15:41,876] [PID 98599] [Dummy-1] [dramatiq.WorkerProcess(0)] [ERROR] Broker connection failed.
Traceback (most recent call last):
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/site-packages/dramatiq/__main__.py", line 246, in worker_process
    module, broker = import_broker(args.broker)
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/site-packages/dramatiq/__main__.py", line 71, in import_broker
    module = importlib.import_module(modname)
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kirkdouglas/Code/e2e/middleman/__init__.py", line 4, in <module>
    @dramatiq.actor
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/site-packages/dramatiq/actor.py", line 94, in actor
    return decorator(fn)
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/site-packages/dramatiq/actor.py", line 89, in decorator
    priority=priority, broker=broker, options=options,
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/site-packages/dramatiq/actor.py", line 120, in __init__
    self.broker.declare_actor(self)
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/site-packages/dramatiq/broker.py", line 175, in declare_actor
    self.declare_queue(actor.queue_name)
  File "/Users/kirkdouglas/.virtualenvs/e2epython3/lib/python3.6/site-packages/dramatiq/brokers/rabbitmq.py", line 202, in declare_queue
    raise ConnectionClosed(e) from None
dramatiq.errors.ConnectionClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'default' in vhost '/': received the value '' of type 'longstr' but current is none")
```

I have rabbitmq running, and haven't changed from default settings on my local machine. Any help?

**Comment by kiorq** [comment]
Yes that was exactly it. Thanks man!

**Comment by Lopofsky** [comment]
In my case I also needed to add permissions manually (despite having them already set at RabbitMQ's Admin section in [localhost:15672](localhost:15672)):

`sudo rabbitmqctl set_permissions -p / <APP_QUEQUE> "." "." ".*"`
