### ISSUE TITLE
[CRITICAL] Consumer encountered an unexpected error

### ISSUE THREAD

**Issue by creatorrr** [Bogdanp/dramatiq#94]
The error is being thrown on start. 

Python runtime: 3.6.3
dramatiq version: 1.2.0
pika version: 0.12.0b4

Stacktrace:
```
[Thread-3] [dramatiq.worker.ConsumerThread(default)] [CRITICAL] Consumer encountered an unexpected error.
Traceback (most recent call last):
File "/app/python3.6/site-packages/dramatiq/worker.py", line 226, in run
for message in self.consumer:
File "/app/python3.6/site-packages/dramatiq/brokers/rabbitmq.py", line 465, in __next__
message = Message.decode(body)
File "/app/python3.6/site-packages/dramatiq/message.py", line 96, in decode
return cls(**global_encoder.decode(data))
TypeError: a bytes-like object is required, not 'NoneType'

```

**Comment by Bogdanp** [comment]
If you need pika 0.12 for whatever reason, you can try out this branch: https://github.com/Bogdanp/dramatiq/pull/81

But it's only going to be merged once 0.12 is officially released.
